[package]
name = "helixer_post_bin"
version = "0.1.0"
authors = ["Tony Bolger <bolger.tony@gmail.com>"]
edition = "2018"

[dependencies]
#hdf5 = "0.8.1"
hdf5-metno = "0.9.2"
ndarray = "0.16.1"
threadpool = "1.0"